version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /scripts/deploy_docker.sh
    mode: "755"
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  DeployDocker:
    - location: scripts/deploy_docker.sh
      timeout: 120
      runas: ubuntu
